#!/usr/bin/env bash
set -euo pipefail

fail=0

need_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "FAIL missing command: $1"
    fail=1
  else
    echo "OK   command: $1"
  fi
}

need_env() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    echo "FAIL missing environment variable: $name"
    fail=1
  else
    echo "OK   environment: $name"
  fi
}

need_min_length() {
  local name="$1"
  local minimum="$2"
  local value="${!name:-}"
  if [ "${#value}" -lt "$minimum" ]; then
    echo "FAIL $name must contain at least $minimum characters"
    fail=1
  else
    echo "OK   length: $name"
  fi
}

need_command docker
need_command curl

if ! docker compose version >/dev/null 2>&1; then
  echo "FAIL docker compose plugin unavailable"
  fail=1
else
  echo "OK   command: docker compose"
fi

need_env PGI_BACKEND_MODE
need_env PGI_AUTH_MODE
need_env POSTGRES_DB
need_env POSTGRES_USER
need_env POSTGRES_PASSWORD
need_env PGI_SESSION_SECRET
need_env PGI_ADMIN_PASSWORD_HASH
need_env PGI_INGEST_TOKEN
need_env PGI_TELEPHONY_USER
need_env PGI_TELEPHONY_PASSWORD
need_env PGI_CALLER_HASH_KEY

if [ "${PGI_BACKEND_MODE:-}" != "production" ]; then
  echo "FAIL PGI_BACKEND_MODE must be production"
  fail=1
fi
if [ "${PGI_AUTH_MODE:-}" != "session" ]; then
  echo "FAIL PGI_AUTH_MODE must be session"
  fail=1
fi

need_min_length PGI_SESSION_SECRET 32
need_min_length PGI_INGEST_TOKEN 24
need_min_length PGI_TELEPHONY_USER 3
need_min_length PGI_TELEPHONY_PASSWORD 24
need_min_length PGI_CALLER_HASH_KEY 32

if [[ "${PGI_ADMIN_PASSWORD_HASH:-}" != scrypt\$* ]]; then
  echo "FAIL PGI_ADMIN_PASSWORD_HASH must be generated by npm run hash:password"
  fail=1
else
  echo "OK   password hash format"
fi

if [ "${PGI_REQUIRE_OPERATOR:-false}" = "true" ]; then
  need_env SVA_NUMBER
  need_env SVA_TARIFF_CODE
  need_env SVA_HOST_CARRIER
  need_env SIP_PRIMARY_HOST
  need_env SIP_TRANSPORT
  need_env SIP_PORT
  echo "INFO operator go-live checks enabled"
else
  echo "INFO operator checks skipped: infrastructure can be validated before carrier selection"
fi

if [ "$fail" -eq 0 ]; then
  if ! docker compose -f infra/docker-compose.production.yml config >/dev/null; then
    echo "FAIL docker compose production configuration is invalid"
    fail=1
  else
    echo "OK   docker compose production configuration"
  fi
fi

if command -v df >/dev/null 2>&1; then
  free_kb="$(df -Pk . | awk 'NR==2 {print $4}')"
  if [ "${free_kb:-0}" -lt 5242880 ]; then
    echo "WARN less than 5 GB free disk space"
  else
    echo "OK   disk space"
  fi
fi

if [ "$fail" -ne 0 ]; then
  echo "Preflight failed."
  exit 1
fi

echo "Preflight passed."
