#!/usr/bin/env bash
set -euo pipefail

fail=0

if [ -n "${PGI_ENV_FILE:-}" ]; then
  if [ ! -r "$PGI_ENV_FILE" ]; then
    echo "FAIL environment file is not readable: $PGI_ENV_FILE"
    exit 1
  fi
  set -a
  # Trusted administrator-owned production environment file.
  # shellcheck disable=SC1090
  source "$PGI_ENV_FILE"
  set +a
fi

need_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "FAIL missing command: $1"
    fail=1
  else
    echo "OK   command: $1"
  fi
}

need_env() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    echo "FAIL missing environment variable: $name"
    fail=1
  else
    echo "OK   environment: $name"
  fi
}

need_min_length() {
  local name="$1"
  local minimum="$2"
  local value="${!name:-}"
  if [ "${#value}" -lt "$minimum" ]; then
    echo "FAIL $name must contain at least $minimum characters"
    fail=1
  else
    echo "OK   length: $name"
  fi
}

need_command docker
need_command curl

if ! docker compose version >/dev/null 2>&1; then
  echo "FAIL docker compose plugin unavailable"
  fail=1
else
  echo "OK   command: docker compose"
fi

need_env PGI_BACKEND_MODE
need_env PGI_AUTH_MODE
need_env PGI_RELEASE_ID
need_env POSTGRES_DB
need_env POSTGRES_USER
need_env POSTGRES_PASSWORD
need_env PGI_SESSION_SECRET
need_env PGI_ADMIN_PASSWORD_HASH
need_env PGI_INGEST_TOKEN
need_env PGI_TELEPHONY_USER
need_env PGI_TELEPHONY_PASSWORD
need_env PGI_CALLER_HASH_KEY
need_env PGI_PORTABILITY_SECRET_KEY

if [ "${PGI_EXTERNAL_BILLING_ENABLED:-false}" = "true" ]; then
  need_env PGI_BILLING_INGEST_TOKEN
  need_env PGI_PUBLIC_BASE_URL
  need_env PGI_STRIPE_SECRET_KEY
  need_env PGI_STRIPE_WEBHOOK_SECRET
  need_env PGI_STRIPE_PORTAL_CONFIGURATION_ID
  echo "INFO Stripe Billing go-live checks enabled"
else
  echo "INFO Stripe Billing checks skipped: external billing disabled"
fi

if [ "${PGI_BACKEND_MODE:-}" != "production" ]; then
  echo "FAIL PGI_BACKEND_MODE must be production"
  fail=1
fi
if [ "${PGI_AUTH_MODE:-}" != "session" ]; then
  echo "FAIL PGI_AUTH_MODE must be session"
  fail=1
fi

case "${PGI_PROCESS_ROLE:-all}" in
  all|api|worker)
    echo "OK   process role: ${PGI_PROCESS_ROLE:-all}"
    ;;
  *)
    echo "FAIL PGI_PROCESS_ROLE must be all, api or worker"
    fail=1
    ;;
esac

if [[ ! "${PGI_RELEASE_ID:-}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "FAIL PGI_RELEASE_ID must be a 40-character Git SHA"
  fail=1
else
  echo "OK   release: ${PGI_RELEASE_ID:0:12}"
fi

backup_keep="${PGI_BACKUP_KEEP_COUNT:-30}"
if [[ ! "$backup_keep" =~ ^[0-9]+$ ]] || [ "$backup_keep" -lt 2 ] || [ "$backup_keep" -gt 365 ]; then
  echo "FAIL PGI_BACKUP_KEEP_COUNT must be between 2 and 365"
  fail=1
else
  echo "OK   backup retention count: $backup_keep"
fi

need_min_length PGI_SESSION_SECRET 32
need_min_length PGI_INGEST_TOKEN 24
need_min_length PGI_TELEPHONY_USER 3
need_min_length PGI_TELEPHONY_PASSWORD 24
need_min_length PGI_CALLER_HASH_KEY 32
need_min_length PGI_PORTABILITY_SECRET_KEY 32

if [[ "${PGI_ADMIN_PASSWORD_HASH:-}" != scrypt\$* ]]; then
  echo "FAIL PGI_ADMIN_PASSWORD_HASH must be generated by npm run hash:password"
  fail=1
else
  echo "OK   password hash format"
fi

# WebAuthn is optional before the production hostname is known, but must be configured atomically.
if { [ -n "${PGI_WEBAUTHN_RP_ID:-}" ] && [ -z "${PGI_WEBAUTHN_ORIGIN:-}" ]; } || { [ -z "${PGI_WEBAUTHN_RP_ID:-}" ] && [ -n "${PGI_WEBAUTHN_ORIGIN:-}" ]; }; then
  echo "FAIL WebAuthn configuration pair incomplete: set both PGI_WEBAUTHN_RP_ID and PGI_WEBAUTHN_ORIGIN"
  fail=1
elif [ -n "${PGI_WEBAUTHN_ORIGIN:-}" ]; then
  if [[ ! "${PGI_WEBAUTHN_ORIGIN}" =~ ^https://[^/]+$ ]]; then
    echo "FAIL PGI_WEBAUTHN_ORIGIN must be an exact HTTPS origin without a path"
    fail=1
  elif [[ "${PGI_WEBAUTHN_RP_ID:-}" == http://* || "${PGI_WEBAUTHN_RP_ID:-}" == https://* || "${PGI_WEBAUTHN_RP_ID:-}" == */* ]]; then
    echo "FAIL PGI_WEBAUTHN_RP_ID must be a hostname without scheme or path"
    fail=1
  else
    echo "OK   WebAuthn configuration pair"
  fi
else
  echo "INFO WebAuthn disabled until the production HTTPS hostname is configured"
fi

if [ "${PGI_REQUIRE_OPERATOR:-false}" = "true" ]; then
  if [ "${PGI_REQUIRE_CARRIER_CONTRACT:-false}" != "true" ]; then
    echo "FAIL PGI_REQUIRE_CARRIER_CONTRACT must be true for operator go-live"
    fail=1
  else
    echo "OK   carrier contract enforcement enabled"
  fi
  need_env SVA_NUMBER
  need_env SVA_TARIFF_CODE
  need_env SVA_HOST_CARRIER
  need_env SIP_PRIMARY_HOST
  need_env SIP_TRANSPORT
  need_env SIP_PORT
  echo "INFO operator go-live checks enabled"
else
  echo "INFO operator checks skipped: infrastructure can be validated before carrier selection"
fi

if [ "$fail" -eq 0 ]; then
  if ! docker compose -f infra/docker-compose.production.yml config >/dev/null; then
    echo "FAIL docker compose production configuration is invalid"
    fail=1
  else
    echo "OK   docker compose production configuration"
  fi
fi

if command -v df >/dev/null 2>&1; then
  free_kb="$(df -Pk . | awk 'NR==2 {print $4}')"
  if [ "${free_kb:-0}" -lt 5242880 ]; then
    echo "WARN less than 5 GB free disk space"
  else
    echo "OK   disk space"
  fi
fi

if [ "$fail" -ne 0 ]; then
  echo "Preflight failed."
  exit 1
fi

echo "Preflight passed."
